# Generated by Django 2.1.5 on 2019-01-22 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0003_character_classeschar'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackberryVine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vine_choice', models.PositiveSmallIntegerField(choices=[(1, 'Blackberry075'), (2, 'Blackberry050'), (3, 'Blackberry025')])),
            ],
        ),
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(choices=[(1, 'Palette'), (2, 'Box'), (3, 'Individual')])),
            ],
        ),
        migrations.AddField(
            model_name='costumer',
            name='ord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnew.Order'),
        ),
        migrations.AddField(
            model_name='costumer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnew.BlackberryVine'),
        ),
    ]
